#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend web_Servers
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
    server 251323-web-01 52.201.181.240
    server 251323-web-02 35.175.64.77
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
