#!/usr/bin/env bash
# Configures an Ubuntu server

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to set localhost and facebook.com addresses
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
