#!/usr/bin/env bash
# Configure Nginx to run as the 'nginx' user and listen on port 8080
pkill apache2
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
